development:
  stripe_secret_key: 'sk_test_51KnXE8GSIN46a590o97sNEMhm9NtdVnNvA2E6YqAJKIX5whJry6XsHqrHWXLdiLEeyqvg8Hd1olqaCDCvl5slmja00TQAmma2q'
  stripe_publishable_key: 'pk_test_51KnXE8GSIN46a590CLn27onXGJiTur1Pa0I5Uu2vYFTEUKJgbdm9Vb523HNTxW362fD70YHsI3nXsjayJesbJzqy00luMjRpsi'